xls:
    path: "demo_data/DPSiPOC.xlsx"
    has_header: True
    min_row: 2
    max_row: 10
    max_column: null

address:
    col_indxs:
        st_name_num: 4
        secondary_place_name: 5
        postal_code: 6
        primary_place_name: 7
        county: 8
        province: 9
    illegal_street_names:
        - "dz."
        - "ew."
        - "dzia³ki"
        - "nr"
        - "obrêb"
    abbrev_expansions:
        "œw.": "œwiêtego"
        "gen.": "genera³a"
    remove_abbrev: False

strict_search: False
